### ISSUE TITLE
Make updated releases

### ISSUE THREAD

**Issue by dfarrell07** [tim-actions/dco#4]
First, thank you for your work to create these useful actions!

I wonder if it would be possible to make updated releases for your `tim-actions/get-pr-commits`, `tim-actions/dco`, and `tim-actions/wip-check` GitHub Actions? I prefer to stick to released versions to avoid possible breakages on master (per [GitHub guidelines](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses)), but would like to get the latest commits (version bumps and such).

**Comment by Tim-Zhang** [comment]
@dfarrell07 done

**Comment by dfarrell07** [comment]
Thank you @Tim-Zhang! :pray:
