### ISSUE TITLE
Improve suggestion on what to do if `--signoff` is missing

### ISSUE THREAD

**Issue by Mo-Gul** [tim-actions/dco#6]
Currently the user "only" receives

https://github.com/tim-actions/dco/blob/f2279e6e62d5a7d9115b0cb8e837b777b1b02e21/libs/helper.js#L9-L12

when not all commits are signed-off.

That is good information on what the user should do *the next time* when contributing to the repo. But it doesn't help much to fix *the current PR*. Since I am only/still a beginner at git I have no good suggestion myself, but had seen

```
git remote update
git rebase --exec 'git commit --amend --no-edit -n -s' @{upstream}
```

in [this comment](https://github.com/pgf-tikz/pgf/pull/1081#issuecomment-984656039). Assuming that this advice is useful, would it be worth to adapt `helper.js` accordingly?

**Comment by gabor-braun** [comment]
Recent git versions have an option `--signoff` for this purpose.
So one could do:

```sh
git remote update
git rebase --signoff @{upstream}
```

**Comment by Mo-Gul** [comment]
Sorry, but I am not very good at using Git, so please excuse a maybe n00bie question.

Should it be sufficient to write exactly that and only that or do I need to replace something like the `@{upstream}`?

I am asking because I tried that with a dummy git repository + a fork, but that didn't work ...

In case I am just to stupid, it would be great if these lines could be shown automatically in the PR. Currently one has to dig into the LOG of the action to see the advice.

Thank you in advance for your time!

**Comment by gabor-braun** [comment]
You have demonstrated that the instructions are not robust enough.  I suggest the following, which should work for a typical setup for clones of the main pgf/tikz repo:

```sh
git fetch origin master
git rebase --signoff origin/master
```

I have changed the first command to download less: just what is needed to be up to date.

---

My guess in your case `@{upstream}` actually referred to your own fork instead of the original repo, and that's why it failed.  I think this would happen to many others, too.  I should have thought of it in my previous answer.

**Comment by Mo-Gul** [comment]
Hmm, also this doesn't work for me. Maybe this is a Windows issue. I tested with [Git for Windows](https://gitforwindows.org/) v2.34.1.

What did work for me is

```
git remote update
git rebase --signoff @~X
git push --force
```

where `X` needs to be replaced by the number of commits which should be signed.

Of course your proposals are **much** better than mine, because I hope that all commits in the PR/branch are signed.

**Comment by Tim-Zhang** [comment]
@Mo-Gul if the last commit missed the sign-off, you can use `git commit --amend -s --no-edit` to resolve.
if the missing commit is not the last one, use `git rebase -i $pre-commit-id` to reword it manually.
